### ISSUE TITLE
Create skill bar plot for a given player

### ISSUE THREAD

**Issue by jerome3o** [Samueljbk/osrs_analysis#15]
- [x] calculate the XP gained for each skill for a given player
- [x] ignore all skills with no xp gain
- [x] plot the XP in a bar graph with the skill as the label and the bar height as the xp gained

**Comment by jerome3o** [comment]
this should be a function in the plot.py module, similar to your relative/absolute skill time series plots

**Comment by Samueljbk** [comment]
Done
