### ISSUE TITLE
sftp data from rpi to pc

### ISSUE THREAD

**Issue by jerome3o** [Samueljbk/osrs_analysis#3]
data is in `rpi:/data/osrs`
- [x] copy them to your pc, in this repo in a `data/` folder using the `sftp` command
- [x] make sure to add data/ to your `.gitignore`
- [x] extra for experts: make a script to do this automatically, you will probably want to use `scp` instead of `sftp`
    - [x] make copy_data.sh
    - [x] add relevant commands to that file (i.e. `scp`)
    - [x] make script runnable (`chmod +x ./copy_data.sh`)
    - [x] try run the script (`./copy_data.sh`)

**Comment by Samueljbk** [comment]
Done
