### ISSUE TITLE
make `loader.py` + add loading function

### ISSUE THREAD

**Issue by jerome3o** [Samueljbk/osrs_analysis#4]
- [x] make a file called `loader.py` where we will put processing code
- [x] make function `load_data_file` that takes in a file path (string), uses the `json` module to load in the data from the provided file, returns the data

**Comment by jerome3o** [comment]
example use

```python
from loader import load_data_file

my_data = load_data_file("data/2023-04-11-05-06.json")

```

**Comment by Samueljbk** [comment]
Done
