### ISSUE TITLE
make load all data function

### ISSUE THREAD

**Issue by jerome3o** [Samueljbk/osrs_analysis#5]
- [ ] using your `load_data_file` function from before, make a `load_data` function that loads all the files in a given directory

**Comment by jerome3o** [comment]
Things you may need to know:
* how to get all files in a folder
* how to loop over all those files (and call your `load_data_file`)

**Comment by jerome3o** [comment]
example

```python
from loader import load_data

all_data = load_data("data/")
```

**Comment by Samueljbk** [comment]
Done
