### ISSUE TITLE
add analysis helper: `get_skill_time_series`

### ISSUE THREAD

**Issue by jerome3o** [Samueljbk/osrs_analysis#8]
`get_skill_time_series`

input:
- `username` (str)
- `skill` (str)
- `all_data` (list of scrapes)
- `skill_attribute` (str) defaults to "experience"

return
- time stamps (list of time stamp numbers)
- list of skill attribute values (list of numbers), i.e. all experience counts.

**Comment by Samueljbk** [comment]
Done
